seobject: Handle python error returns correctly
Following commit 9792099f (Properly build the swig exception file even if the headers are missing),
the underlying semanage_fcontext_query_local and semanage_fcontext_query calls result in an OSError
return. This results in the following error when attempting to modify a fcontext defined in the
systems base policy.

    libsemanage.dbase_llist_query: could not query record value (No such file or directory).
    OSError: No such file or directory

To resolve the error, handle the OSError exception, but retain the previous query operation.

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1398427

Signed-off-by: Kyle Walker <kwalker@redhat.com>