sandbox/sandbox: fix saving file changes
Fixes the following backtrace on saving files:

  $ sandbox -M -H sandbox_home/ -T sandbox_tmp/ /usr/bin/vim sandbox_home/cmd
  [edit file and save]
  Traceback (most recent call last):
    File "/usr/bin/sandbox", line 565, in <module>
      rc = sandbox.main()
    File "/usr/bin/sandbox", line 553, in main
      return self.__execute()
             ~~~~~~~~~~~~~~^^
    File "/usr/bin/sandbox", line 530, in __execute
      savefile(dest, i, self.__options.X_ind)
      ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/bin/sandbox", line 133, in savefile
      ans = input(_("Do you want to save changes to '%s' (y/N): ") % orig)
            ^^^^^
  UnboundLocalError: cannot access local variable 'input' where it is not associated with a value

Signed-off-by: Robert Frohl <rfrohl@suse.com>
Acked-by: Stephen Smalley <stephen.smalley.work@gmail.com>