gui: remove selinux-polgengui application
polgengui.py is not compatible with Gtk3, Python 3, etc. Moreover it
fails to load at least since the release 2.6-rc1:

$ python2 /usr/share/system-config-selinux/polgengui.py
Traceback (most recent call last):
  File "/usr/share/system-config-selinux/polgengui.py", line 778, in <module>
    app = childWindow()
  File "/usr/share/system-config-selinux/polgengui.py", line 205, in __init__
    self.all_types = sepolicy.generate.get_all_types()
AttributeError: 'module' object has no attribute 'generate'

In fact, this bug has been introduced more than a year ago by commit
b43991f9135e ("policycoreutils: import sepolicy directly"), which
replaced "from sepolicy import generate" with "import sepolicy" instead
of "import sepolicy.generate".

As no one seems to have noticed, this application seems to be no longer
used. Remove it from gui/.

Signed-off-by: Nicolas Iooss <nicolas.iooss@m4x.org>