sandbox: drop unused macro
    seunshare.c:55:9: error: macro is not used [-Werror,-Wunused-macros]
    #define BUF_SIZE 1024
            ^

Signed-off-by: Christian Göttsche <cgzones@googlemail.com>
Acked-by: Stephen Smalley <stephen.smalley.work@gmail.com>